MODEL:
  PRETRAIN_CHOICE: 'imagenet'
  PRETRAIN_PATH: '/xxx/pretrain/ViT-B-16.pt'
  METRIC_LOSS_TYPE: 'triplet'
  IF_LABELSMOOTH: 'off'
  IF_WITH_CENTER: 'no'
  NAME: 'APC'
  NO_MARGIN: False
  DEVICE_ID: ('0')
  TRANSFORMER_TYPE: 'vit_base_patch16_224_TransReID'
  STRIDE_SIZE: [12, 12]
  SIE_CAMERA: True
  SIE_COE: 3.0

INPUT:
  SIZE_TRAIN: [256, 128]
  SIZE_TEST: [256, 128]
  PROB: 0.5 # random horizontal flip
  RE_PROB: 0.5 # random erasing
  PADDING: 10
  PIXEL_MEAN: [0.5, 0.5, 0.5]
  PIXEL_STD: [0.5, 0.5, 0.5]

DATALOADER:
  SAMPLER: 'softmax_triplet'
  NUM_INSTANCE: 4
  NUM_WORKERS: 4

SOLVER:
  OPTIMIZER_NAME: "Adam"
  BASE_LR: 0.0000075
  MAX_EPOCHS: 60
  IMS_PER_BATCH: 64
  WARMUP_METHOD: 'linear'
  LARGE_FC_LR: False
  CHECKPOINT_PERIOD: 120
  LOG_PERIOD: 50
  EVAL_PERIOD: 20
  WEIGHT_DECAY:  1e-4
  WEIGHT_DECAY_BIAS: 1e-4
  BIAS_LR_FACTOR: 2

TEST:
  EVAL: True
  IMS_PER_BATCH: 64
  RE_RANKING: False
  WEIGHT: '/xxx/q_model_120.pth'
  NECK_FEAT: 'before'
  FEAT_NORM: 'yes'
  REPORT_SAMPLE: True

DATASETS:
   TYPE: 'image'
   NAMES: ('cuhk03', 'market1501', 'duke')
   TARGET_NAMES: ('msmt17')
   ROOT_DIR: ('/xxx/datasets/')
OUTPUT_DIR: '/xxx/output/APC/'

